#!/bin/bash

RED=$(tput setaf 1)
NORMAL=$(tput sgr0)

######### PRINT RED STD ##################
function rprint (){
    echo -e >&2 "${RED}$1${NORMAL}";
}

test -n "$(grep '^Signed-off-by: ' "${1}")" >/dev/null || {
        rprint "\nThe commit message must have a Signed-off-by line."
        rprint "To sign-off:\n\t git commit -s\n"
        exit 1
    }
