#!/bin/bash

RED=$(tput setaf 1)
NORMAL=$(tput sgr0)

######### PRINT RED STD ##################
function rprint (){
    echo -e >&2 "${RED}$1${NORMAL}";
}

test -n "$(grep '^Signed-off-by: ' "${1}")" >/dev/null || {
        SIGNOFF="Signed-off-by: $(git config user.name) <$(git config user.email)>"
        echo "" >> "$1"
        echo "${SIGNOFF}" >> "$1"
        exit 0
    }
