#!/usr/bin/env bash
# Git pre-push hook, that will automagically run a Jenkins build.
AUTHOR="Mpho Mphego <mmphego@ska.ac.za>"

set -i

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

declare -a PYTHON_PKG="(corr2 casperfpga mkat_fpga)"
REPO=$(basename `git rev-parse --show-toplevel`) # get current repository name
BRANCH=$(git rev-parse --abbrev-ref HEAD)
HOST="cmc3.cbf.mkat.karoo.kat.ac.za"
PORT="8080"
TOKEN="cbftests"

function gprint (){
    printf "${GREEN}$1 ${NORMAL}\n";
}

function rprint (){
    printf "${RED}$1 ${NORMAL}\n";
}

if curl --output /dev/null --silent --head --fail "http://${HOST}:${PORT}"; then
    for pkg in "${PYTHON_PKG[@]}"; do
        if [ "${pkg}" = "${REPO}" ] && [ "${BRANCH}" = "devel" ]; then
            gprint "Running tests to check for new bugs on ${REPO}";
            gprint "Open: http://${HOST}:${PORT} to see progress...";
            curl -X POST "http://${HOST}:${PORT}/generic-webhook-trigger/invoke?token=${TOKEN}" > /dev/null 2>&1;
        fi;
    done
else
    rprint "http://${HOST}:${PORT} IS DOWN!!!!!!";
    rprint "Contact: ${AUTHOR}";
fi
